config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :notices
  resources :qnas
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/auth/kakao', to: 'users/omniauth_callbacks#kakao'
    get '/users/auth/kakao/callback', to: 'users/omniauth_callbacks#kakao_auth'
  end
  get '/info' => 'home#info'

  get '/products/index_penalty'   => 'products#index_penalty'
  get '/products/new_penalty'     => 'products#new_penalty'
  resources :products
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/product_new'  => 'products#new_map'
  post '/product_map' => 'products#create_map'
    
  get '/smovesmoveadmin'                     => 'admin_pages#index'
  get '/smovesmoveadmin/show_user'           => 'admin_pages#show_user'
  get '/smovesmoveadmin/show_nsmoking'       => 'admin_pages#show_nsmoking'
  get '/smovesmoveadmin/show_smoke_place'    => 'admin_pages#show_smoke_place'
  get '/smovesmoveadmin/show_qna'            => 'admin_pages#show_qna'
  get '/smovesmoveadmin/show_notice'         => 'admin_pages#show_notice'
  get '/smovesmoveadmin/show_penalty_place'  => 'admin_pages#show_penalty_place'
  get '/smovesmoveadmin/nsmoking_areas'      => 'admin_pages#nsmoking_areas'
  get '/smovesmoveadmin/login'               => 'admin_pages#login'
  get '/smovesmoveadmin/new_notice'          => 'admin_pages#new_notice'  
    
  get '/smovesmoveadmin/edit_notice'          => 'admin_pages#edit_notice'  

  get '/likes/:product_id/home' => 'home#like_product'
  get '/likes/:product_id/product' => 'products#like_product'
  
    
end

app/models/notice.rb
class Notice < ApplicationRecord
    # belongs_to :user    
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :user_pages
  before_action :authenticate_user! 
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
    
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to '/smovesmoveadmin/show_notice', success: '공지사항을 등록하였습니다.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to '/smovesmoveadmin/show_notice', notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to '/smovesmoveadmin/show_notice', notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:title, :content, :count)
    end
    
    def user_pages
      @user_pages = true
    end
    
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<%= form_for(notice) do |f| %>
<div class = "card-body">
<div class="py-4 text-center">
  <div class = "from-group mx-auto" style="width:200px">
    공지사항 제목 : <br/>
    <%=f.text_field :title, id: 'lat' ,class: "form-control"%>
  </div>
  <div class = "from-group mx-auto" style="width:200px">
    내용 <br/>
    <%=f.text_area :content, id: 'lng' ,class: "form-control"%><br/>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit "등록하기",class: 'btn btn-primary'%>
  </div>
</div>
</div>
<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
        <!-- start head bottom -->
      <div class="bottom">
        <div class="left">
          <h1>공지사항</h1>
        </div>
        <div class="right">
        </div>
      </div>
      <!-- end head bottom -->

<div class= "">
  <br>
<div class="col-md-12">
	<div class="widget p-lg">
		<h4 class="m-b-lg"></h4>
		<p class="m-b-lg docs">
		</p>

		<table class="table table-bordered">
			<tr><th>번호</th><th>제목</th><th>등록 시간</th></tr>
    <% @notices.each do |notice| %>
			<tr><td><%= notice.id %></td><td><%= link_to notice.title, '/' %></td><td><%= notice.created_at.strftime("%Y년 %m월 %d일 %H시 %M분") %></td></tr>
    <% end %>
		</table>
	</div><!-- .widget -->
</div><!-- END column -->    
</div>

<% content_for 'javascript_content' do %>
  <%= javascript_include_tag params[:controller] %>
  <script>
  </script>
<% end %>



<!--제목의 글을 눌렀을 때 해당 글을 볼 수 있도록 들어감.-->

<!--<table>-->
<!--  <thead >-->
<!--    <tr>-->
<!--      <th class="col-5">제목</th>-->
<!--      <th class="col-1">조회수</th>-->
<!--      <th class="col-3">날짜</th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--    <@% @notices.each do |notice| %>-->
<!--      <tr>-->
<!--        <td><@%= notice.title %></td>-->
<!--        <td><@%= notice.count %></td>-->
<!--        <td><@%= notice.created_at %></td>-->
        <!--<td><%#= link_to 'Show', notice %></td>-->
        <!--<td><%#= link_to 'Edit', edit_notice_path(notice) %></td>-->
        <!--<td><%#= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
<!--    <@% end %>-->
<!--  </tbody>-->
<!--</table>-->

<br>

app/views/notices/new.html.erb
<h1>New Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @notice.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @notice.content %>
</p>

<p>
  <strong>Count:</strong>
  <%= @notice.count %>
</p>

<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>