config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :notices
  resources :qnas
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/auth/kakao', to: 'users/omniauth_callbacks#kakao'
    get '/users/auth/kakao/callback', to: 'users/omniauth_callbacks#kakao_auth'
  end
  get '/info' => 'home#info'

  get '/products/index_penalty'   => 'products#index_penalty'
  get '/products/new_penalty'     => 'products#new_penalty'
  resources :products
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/product_new'  => 'products#new_map'
  post '/product_map' => 'products#create_map'
    
  get '/smovesmoveadmin'                     => 'admin_pages#index'
  get '/smovesmoveadmin/show_user'           => 'admin_pages#show_user'
  get '/smovesmoveadmin/show_nsmoking'       => 'admin_pages#show_nsmoking'
  get '/smovesmoveadmin/show_smoke_place'    => 'admin_pages#show_smoke_place'
  get '/smovesmoveadmin/show_qna'            => 'admin_pages#show_qna'
  get '/smovesmoveadmin/show_notice'         => 'admin_pages#show_notice'
  get '/smovesmoveadmin/show_penalty_place'  => 'admin_pages#show_penalty_place'
  get '/smovesmoveadmin/nsmoking_areas'      => 'admin_pages#nsmoking_areas'
  get '/smovesmoveadmin/login'               => 'admin_pages#login'
  get '/smovesmoveadmin/new_notice'          => 'admin_pages#new_notice'  
    
  get '/smovesmoveadmin/edit_notice'          => 'admin_pages#edit_notice'  

  get '/likes/:product_id/home' => 'home#like_product'
  get '/likes/:product_id/product' => 'products#like_product'
  
    
end

app/models/qna.rb
class Qna < ApplicationRecord
    
    # belongs_to :user
end

app/controllers/qnas_controller.rb
class QnasController < ApplicationController
  before_action :user_pages
  before_action :authenticate_user!
  before_action :set_qna, only: [ :show, :edit, :update, :destroy]
  
  # GET /qnas
  # GET /qnas.json
  def index
    @qnas = Qna.all
  end

  # GET /qnas/1
  # GET /qnas/1.json
  def show
  end

  # GET /qnas/new
  def new
    @qna = Qna.new
  end

  # GET /qnas/1/edit
  def edit
  end

  # POST /qnas
  # POST /qnas.json
  def create
    @qna = Qna.new(qna_params)
    respond_to do |format|
      if @qna.save
        format.html { redirect_to '/', info: '문의사항이 전달되었습니다.'  }
        format.json { render :show, status: :created, location: @qna }
      else
        format.html { render :new }
        format.json { render json: @qna.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qnas/1
  # PATCH/PUT /qnas/1.json
  def update
    respond_to do |format|
      if @qna.update(qna_params)
        format.html { redirect_to @qna, notice: 'Qna was successfully updated.' }
        format.json { render :show, status: :ok, location: @qna }
      else
        format.html { render :edit }
        format.json { render json: @qna.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qnas/1
  # DELETE /qnas/1.json
  def destroy
    @qna.destroy
    respond_to do |format|
      format.html { redirect_to qnas_url, notice: 'Qna was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qna
      @qna = Qna.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qna_params
      params.require(:qna).permit(:user_name, :title, :content, :answer_email)
    end
    
    def user_pages
      @user_pages = true
    end
    
end

app/helpers/qnas_helper.rb
module QnasHelper
end

app/views/qnas/_form.html.erb
<div class = "card-body">
<div class = "card-head">
        		<div class="row">
          			<div class="col-lg-12">
        				  <form action="/qnas" class="form-horizontal" method="post">
        				  	<div class = "card-body">
          					<div class="row">
          						<div class="col-md-12">
          							<div class="m-b-lg"><h5>
          								문의하실 내용을 다음 아래 항목에 적어주신 후 <code>보내기</code> 버튼을 눌러주세요.
          							</h5></div>
          						</div>
          					</div>
          					</div>
          					<br>
        					<div class="form-group has-success has-feedback">
        					  <input type="hidden" value="<%= form_authenticity_token() %>"  name="authenticity_token"/>
        						<label class="control-label col-sm-3 text-left" for="inputSuccess2">이용자 ID</label>
        						<div class="col-sm-12">
        							<input  type="text" class="form-control" name="qna[user_name]" id="qna_user_name" aria-describedby="inputSuccess2Status">
        						</div>
        						<br>
        						<label class="control-label col-sm-3 text-left" for="inputSuccess2"> 제목 </label>
    								<div class="col-sm-12">
        					    <input class="form-control" type="text" name="qna[title]" id="qna_title"  aria-describedby="inputSuccess2Status">
										</div>
        						<br>
        						<label class="control-label col-sm-3 text-left" for="inputSuccess2"> 문의 내용 </label>
    								<div class="col-sm-12">
        					    <textarea class="form-control" name="qna[content]" id="qna_content" aria-describedby="inputSuccess2Status"> </textarea>
										</div>
										<br>
        						<label class="control-label col-sm-3 text-left" for="inputSuccess2"> 답장 받으실 이메일 주소 </label>
    								<div class="col-sm-12">
        					    <input class="form-control" type="text" name="qna[answer_email]" id="qna_answer_email" aria-describedby="inputSuccess2Status">
										</div>
										<br>
					<div class = "card-body">					
					<div class="actions">
                      <input type="submit" name="commit" value="보내기" data-disable-with="보내기" class = "btn btn-primary"><br>
                    </div>
                    </div>
                    </form>
        					</div>
      					</div>
    					</div>
    					</div>

</div>

        					
        					<!--<div class="form-group has-warning has-feedback">-->
        					<!--	<label class="control-label col-sm-3 text-left" for="inputWarning2">Input with warning</label>-->
        					<!--	<div class="col-sm-12">-->
        					<!--		<input  type="text" class="form-control" id="inputWarning2" aria-describedby="inputWarning2Status">-->
        					<!--		<span class="glyphicon glyphicon-warning-sign form-control-feedback" aria-hidden="true"></span>-->
        					<!--		<span id="inputWarning2Status" class="sr-only">(warning)</span>-->
        					<!--	</div>-->
        					<!--</div>-->

        					<!--<div class="form-group has-error has-feedback">-->
        					<!--	<label class="control-label col-sm-3 text-left" for="inputError2">Input with error</label>-->
        					<!--	<div class="col-sm-12">-->
        					<!--		<input  type="text" class="form-control" id="inputError2" aria-describedby="inputError2Status">-->
        					<!--		<span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>-->
        					<!--		<span id="inputError2Status" class="sr-only">(error)</span>-->
        					<!--	</div>-->
        					<!--</div>-->
        					<!--<div class="form-group">-->
        					<!--	<label for="control-demo-5" class="col-sm-3">Textarea</label>-->
        					<!--	<div class="col-sm-12">-->
        					<!--		<textarea name="control-demo-5" id="control-demo-5" class="form-control" cols="30" rows="10"></textarea>-->
        					<!--	</div>-->
        					<!--</div><!-- .form-group --> 

app/views/qnas/edit.html.erb
<h1>Editing Qna</h1>

<%= render 'form', qna: @qna %>

<%= link_to 'Show', @qna %> |
<%= link_to 'Back', qnas_path %>

app/views/qnas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Qnas</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Title</th>
      <th>Content</th>
      <th>Answer email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qnas.each do |qna| %>
      <tr>
        <td><%= qna.user_name %></td>
        <td><%= qna.title %></td>
        <td><%= qna.content %></td>
        <td><%= qna.answer_email %></td>
        <td><%= link_to 'Show', qna %></td>
        <td><%= link_to 'Edit', edit_qna_path(qna) %></td>
        <td><%= link_to 'Destroy', qna, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qna', new_qna_path %>

app/views/qnas/new.html.erb
        <!-- start head bottom -->
      <div class="bottom">
        <div class="left">
          <h1>문의사항</h1>
        </div>
        <div class="right">
          <!--<h1>dashboard /</h1>-->
          <!--<a href="#">page name</a>-->
        </div>
      </div>
      <!-- end head bottom -->
      
<%= render 'form', qna: @qna %>

<!--<#%= link_to '뒤로 가기', qnas_path %>-->


    
    <% content_for 'javascript_content' do %>
  <%= javascript_include_tag params[:controller] %>
  <script>
  </script>
<% end %>

app/views/qnas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @qna.user_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @qna.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @qna.content %>
</p>

<p>
  <strong>Answer email:</strong>
  <%= @qna.answer_email %>
</p>

<%= link_to 'Edit', edit_qna_path(@qna) %> |
<%= link_to 'Back', qnas_path %>