config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :notices
  resources :qnas
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get '/users/auth/kakao', to: 'users/omniauth_callbacks#kakao'
    get '/users/auth/kakao/callback', to: 'users/omniauth_callbacks#kakao_auth'
  end
  get '/info' => 'home#info'

  get '/products/index_penalty'   => 'products#index_penalty'
  get '/products/new_penalty'     => 'products#new_penalty'
  resources :products
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/product_new'  => 'products#new_map'
  post '/product_map' => 'products#create_map'
    
  get '/smovesmoveadmin'                     => 'admin_pages#index'
  get '/smovesmoveadmin/show_user'           => 'admin_pages#show_user'
  get '/smovesmoveadmin/show_nsmoking'       => 'admin_pages#show_nsmoking'
  get '/smovesmoveadmin/show_smoke_place'    => 'admin_pages#show_smoke_place'
  get '/smovesmoveadmin/show_qna'            => 'admin_pages#show_qna'
  get '/smovesmoveadmin/show_notice'         => 'admin_pages#show_notice'
  get '/smovesmoveadmin/show_penalty_place'  => 'admin_pages#show_penalty_place'
  get '/smovesmoveadmin/nsmoking_areas'      => 'admin_pages#nsmoking_areas'
  get '/smovesmoveadmin/login'               => 'admin_pages#login'
  get '/smovesmoveadmin/new_notice'          => 'admin_pages#new_notice'  
    
  get '/smovesmoveadmin/edit_notice'          => 'admin_pages#edit_notice'  

  get '/likes/:product_id/home' => 'home#like_product'
  get '/likes/:product_id/product' => 'products#like_product'
  
    
end

app/models/admin_page.rb
class AdminPage < ApplicationRecord
    
  has_many :products
  has_many :qnas
  has_many :notices
  has_many :homes
  has_many :users
    
end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
    before_action :master_id_confirm
    before_action :admin_pages

    
    def index
    end
    
    def show_nsmoking
        @nsmoke_places = Home.all
    end
    
    def show_user
        @users = User.all
    end
    
    def show_smoke_place
        @smoke_places = Product.all
    end
    
    def show_penalty_place
        @penalty_places = Product.all
    end
    
    def new_qna
        @notices = Notice.new 
    end
    
    def show_qna
        @qnas = Qna.all
    end
    
    def new_notice
        @notices = Notice.new    
    end
    
    def edit_notice
       @notices = Notice.all 
    end
    
    
    def show_notice
        @notices = Notice.all
    end
    
    def login
    end
    
    
    def admin_pages
       @admin_pages = true
    end
    
    private
    
    def master_id_confirm
        if current_user.nil?
            redirect_to '/'
        else
            @a = current_user   #    master_id        where / find    그것의 마스터 값을 true인지 확인하기.
            unless @a.masters_id == true
                redirect_to '/'
        end
        end
    end
    
end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/views/admin_pages/_form.html.erb
<%= form_for(notice) do |f| %>

<div class="py-4 text-center">
  <div class = "from-group mx-auto" style="width:200px">
    공지사항 제목 : <br/>
    <%=f.text_field :title, id: 'lat' ,class: "form-control"%>
  </div>
  <div class = "from-group mx-auto" style="width:200px">
    내용 <br/>
    <%=f.text_area :content, id: 'lng' ,class: "form-control"%><br/>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit "등록하기",class: 'btn btn-primary'%>
  </div>
</div>
<% end %>

app/views/admin_pages/index.html.erb
    <!-- start head bottom -->
    <div class="bottom">
      <div class="left">
        <h1>관리자 메인 페이지</h1>
      </div>
      <div class="right">
        <!--<h1>dashboard /</h1>-->
        <!--<a href="#">page name</a>-->
      </div>
    </div>
    <!-- end head bottom -->
  <div class="container">
    </div>

<% content_for 'javascript_content' do %>
  <%= javascript_include_tag params[:controller] %>
  <script>
  </script>
<% end %>

app/views/admin_pages/login.html.erb
<로그인 페이지>

app/views/admin_pages/new_notice.html.erb
        <!-- start head bottom -->
      <div class="bottom">
        <div class="left">
          <h1>공지사항 등록하기</h1>
        </div>
        <div class="right">
        </div>
      </div>


<%= render 'notices/form', notice: @notices %>

<%= link_to '뒤로가기', smovesmoveadmin_show_notice_path, class: 'btn btn-primary' %>

  <% content_for 'javascript_content' do%>
<%= javascript_include_tag params[:controller] %>
<%end%>

app/views/admin_pages/show_notice.html.erb
    <!-- start head bottom -->
    <div class="bottom">
      <div class="left">
        <h1>관리자 페이지</h1>
      </div>
      <div class="right">
        <h1><a href="/smovesmoveadmin/new_notice" style="btn btn-primary">등록하기</a></h1>
        <!--<a href="#">page name</a>-->
      </div>
    </div>
    <br>
<div class="col-md-12">
	<div class="widget p-lg">
		<h4 class="m-b-lg">공지사항 페이지</h4>
		<p class="m-b-lg docs">
			유저들에게 남기고 싶은 공지사항을 기록해주세요.
		</p>

		<table class="table table-bordered">
			<tr><th>번호</th><th>제목</th><th>날짜</th><th>관리</th></tr>
    <% @notices.each do |notice| %>
			<tr><td><%= notice.id %></td><td> <%= notice.title %> </td><td><%= notice.created_at.strftime("%Y년 %m월 %d일 %H시 %M분") %></td><td>
        <%= link_to '수정', edit_notice_path(notice.id) %> | 
			  <%= link_to '삭제', notice_path(notice.id), method: "DELETE", data: { confirm: "공지사항을 삭제 하시겠습니까?" }%>
</td></tr>
    <% end %>
		</table>
	</div><!-- .widget -->
</div><!-- END column -->    


<% content_for 'javascript_content' do %>
  <%= javascript_include_tag params[:controller] %>
  <script>
  </script>
<% end %>

app/views/admin_pages/show_nsmoking.html.erb
    <!-- start head bottom -->
    <div class="bottom">
      <div class="left">
        <h1>관리자 페이지</h1>
      </div>
      <div class="right">
        <!--<h1>dashboard /</h1>-->
        <!--<a href="#">page name</a>-->
      </div>
    </div>
    <br>
<div class="col-md-12">
	<div class="widget p-lg">
		<h4 class="m-b-lg">금연구역 페이지</h4>
		<p class="m-b-lg docs">
			공공데이터 포털에서 찾아온 금연구역 자료를 관리해주세요.
		</p>

		<table class="table table-bordered">
			<tr><th>번호</th><th>장소명</th><th>장소분류</th><th>위도</th><th>경도</th><th>주소</th><th>등록시간</th></tr>
    <% @nsmoke_places.each do |nsmoke_place| %>
			<tr><td><%= nsmoke_place.id %></td><td><%=nsmoke_place.area_name %></td><td><%=nsmoke_place.area_catagory %></td><td><%=nsmoke_place.latitude %></td><td><%=nsmoke_place.longitude %></td><td><%=nsmoke_place.address %></td><td><%= nsmoke_place.created_at.strftime("%Y년 %m월 %d일 %H시 %M분") %></td></tr>
    <% end %>
		</table>
	</div><!-- .widget -->
</div><!-- END column -->        
    
    
    
    
    
<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th class="col">장소명</th>-->
<!--      <th class="col">장소분류</th>-->
<!--      <th class="col">위도</th>-->
<!--      <th class="col">경도</th>-->
<!--      <th class="col">주소</th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--      <@% @nsmoke_places.each do |nsmoke_place| %>-->
<!--        <tr>-->
<!--          <td><@%= nsmoke_place.area_name %></td>-->
<!--          <td><@%= nsmoke_place.area_catagory %></td>-->
<!--          <td><@%= nsmoke_place.latitude %></td>-->
<!--          <td><@%= nsmoke_place.longitude %></td>-->
<!--          <td><@%= nsmoke_place.address %></td>-->
<!--          <td><@%= link_to 'Edit', edit_notice_path(notice) %></td>-->
<!--          <td><@%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--        </tr>-->
<!--      <@% end %>-->
      
<!--  </tbody>-->
<!--</table>-->



<% content_for 'javascript_content' do %>
  <%= javascript_include_tag params[:controller] %>
  <script>
  </script>
<% end %>

app/views/admin_pages/show_penalty_place.html.erb
    <!-- start head bottom -->
    <div class="bottom">
      <div class="left">
        <h1>관리자 페이지</h1>
      </div>
      <div class="right">
        <!--<h1>dashboard /</h1>-->
        <!--<a href="#">page name</a>-->
      </div>
    </div>
    <br>
<div class="col-md-12">
	<div class="widget p-lg">
		<h4 class="m-b-lg">단속구역 페이지</h4>
		<p class="m-b-lg docs">
			유저들이 등록한 단속구역을 관리해주세요.
		</p>

		<table class="table table-bordered">
			<tr><th>번호</th><th>장소명</th><th>장소설명</th><th>사진</th><th>등록일자</th><th>신고건수</th><th>관리</th></tr>
    <% @penalty_places.each do |penalty_place| %>
    <% if penalty_place.area_type.eql?("단속구역") %>
			<tr><td><%= penalty_place.id %></td><td><%=penalty_place.area_name %></td><td><%=penalty_place.description %></td><td><%=penalty_place.image_address %></td><td><%= penalty_place.created_at.strftime("%Y년 %m월 %d일 %H시 %M분") %></td>		
		<td><%= penalty_place.likes.count %>
		  </td>
		<td>
    <%= link_to '수정', edit_product_path(penalty_place.id) %> | 
		<%= link_to '삭제', product_path(penalty_place.id), method: "DELETE", data: { confirm: "단속구역을 삭제 하시겠습니까?" } %> 
    </td></tr>
    <% end %>
        <% end %>
		</table>
	</div><!-- .widget -->
</div><!-- END column -->        
    
    
    
    <% content_for 'javascript_content' do %>
  <%= javascript_include_tag params[:controller] %>
  <script>
  </script>
<% end %>

app/views/admin_pages/show_qna.html.erb
    <!-- start head bottom -->
    <div class="bottom">
      <div class="left">
        <h1>관리자 페이지</h1>
      </div>
      <div class="right">
        <!--<h1>dashboard /</h1>-->
        <!--<a href="#">page name</a>-->
      </div>
    </div>
    <br>
<div class="col-md-12">
	<div class="widget p-lg">
		<h4 class="m-b-lg">문의사항 페이지</h4>
		<p class="m-b-lg docs">
			유저들이 등록한 문의사항 내용을 관리해주세요.
		</p>

		<table class="table table-bordered">
			<tr><th>번호</th><th>제목</th><th>내용</th><th>유저명</th><th>이메일</th><th>등록시간</th><th>답변여부</th></tr>
    <% @qnas.each do |qna| %>
			<tr><td><%= qna.id %></td><td><%=qna.title %></td><td><%=qna.content %></td><td><%=qna.user_name %></td><td><%=qna.answer_email %></td><td><%= qna.created_at.strftime("%Y년 %m월 %d일 %H시 %M분") %></td><td> 답변여부</td></tr>
    <% end %>
		</table>
	</div><!-- .widget -->
</div><!-- END column -->        
    

<!--<thead>-->
<!--    <tr>-->
<!--      <th class="col">제목</th>-->
<!--      <th class="col">내용</th>-->
<!--      <th class="col">유저명</th>-->
<!--      <th class="col">이메일</th>-->
<!--      <th class="col">등록시간</th>      -->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--      <@% @qnas.each do |qna| %>-->
<!--        <tr>-->
<!--          <td><@%= qna.title %></td>-->
<!--          <td><@%= qna.content %></td>-->
<!--          <td><@%= qna.user_name %></td>-->
<!--          <td><@%= qna.answer_email %></td>-->
<!--          <td><@%= qna.created_at %></td>-->
          <!--<td><%#= link_to 'Show', notice %></td>-->
          <!--<td><%#= link_to 'Edit', edit_notice_path(notice) %></td>-->
          <!--<td><%#= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--        </tr>-->
<!--      <@% end %>-->
      
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->



<% content_for 'javascript_content' do %>
  <%= javascript_include_tag params[:controller] %>
  <script>
  </script>
<% end %>

app/views/admin_pages/show_smoke_place.html.erb
    <!-- start head bottom -->
    <div class="bottom">
      <div class="left">
        <h1>관리자 페이지</h1>
      </div>
      <div class="right">
        <!--<h1>dashboard /</h1>-->
        <!--<a href="#">page name</a>-->
      </div>
    </div>
    <br>
<div class="col-md-12">
	<div class="widget p-lg">
		<h4 class="m-b-lg">흡연구역 페이지</h4>
		<p class="m-b-lg docs">
			유저들이 등록한 흡연구역을 관리해주세요.
		</p>

		<table class="table table-bordered">
			<tr><th>번호</th><th>장소명</th><th>장소설명</th><th>사진</th><th>등록일자</th><th>신고건수</th><th>관리</th></tr>
    <% @smoke_places.each do |smoke_place| %>
    <% if smoke_place.area_type.eql?("흡연구역") %>
			<tr><td><%= smoke_place.id %></td><td><%=smoke_place.area_name %></td><td><%=smoke_place.description %></td><td><%=smoke_place.image_address %></td><td><%= smoke_place.created_at.strftime("%Y년 %m월 %d일 %H시 %M분") %></td>
				<td><%= smoke_place.likes.count %>
		  </td>
		<td>
    <%= link_to '수정', edit_product_path(smoke_place.id) %> | 
		<%= link_to '삭제', product_path(smoke_place.id), method: "DELETE",  data: { confirm: "흡연구역을 삭제 하시겠습니까?" } %>
    </td></tr>
    <% end %>
        <% end %>
		</table>
	</div><!-- .widget -->
</div><!-- END column -->    
    
    
    <!--<#%= link_to '수정', edit_notice_path(notice), class: "btn btn-info"%> |
    <@%= link_to '삭제', notice, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info"%></td>-->
    
    <% content_for 'javascript_content' do %>
  <%= javascript_include_tag params[:controller] %>
  <script>
  </script>
<% end %>



<% content_for 'javascript_content' do %>
  <%= javascript_include_tag params[:controller] %>
  <script>
  </script>
<% end %>

app/views/admin_pages/show_user.html.erb
    <!-- start head bottom -->
    <div class="bottom">
      <div class="left">
        <h1>관리자 페이지</h1>
      </div>
      <div class="right">
        <!--<h1>dashboard /</h1>-->
        <!--<a href="#">page name</a>-->
      </div>
    </div>
    <br>
<div class="col-md-12">
	<div class="widget p-lg">
		<h4 class="m-b-lg">유저관리 페이지</h4>
		<p class="m-b-lg docs">
			회원가입한 회원들을 관리해주세요.
		</p>

		<table class="table table-bordered">
			<tr><th>번호</th><th>이메일</th><th>게시글 수</th><th>접속날짜</th><th>로그인 횟수</th><th>상태(탈퇴처리)</th></tr>
    <% @users.each do |user| %>
			<tr><td><%= user.id %></td><td><%=user.email %></td><td></td><td><%=user.last_sign_in_at %></td><td><%=user.sign_in_count%></td><td>
			<%= link_to '탈퇴처리', '/users' , method: "DELETE", data: { confirm: "해당 유저를 삭제 하시겠습니까?" } %>
			</td></tr>
    <% end %>
		</table>
	</div><!-- .widget -->
</div><!-- END column -->        
    
<!--<table>-->
<!--  <thead >-->
<!--    <tr>-->
<!--      <th class="col">유저명</th>-->
<!--      <th class="col">이메일</th>      -->
<!--      <th class="col">게시글 수</th>-->
<!--      <th class="col">접속날짜</th>-->
<!--      <th class="col">상태(탈퇴처리)</th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--      <@% @users.each do |user| %>-->
<!--        <tr>-->
<!--          <td><@%= user.user_name %></td>-->
<!--          <td><@%= user.email %></td>-->
<!--          <td><%#= user.      %></td>
<!--          <td><@%= user.last_sign_in_at %></td>-->
<!--          <td><@%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
          <!--<td><%#= link_to 'Show', notice %></td>-->
          <!--<td><%#= link_to 'Edit', edit_notice_path(notice) %></td>-->
          <!--<td></td>-->
<!--        </tr>-->
<!--      <@% end %>-->
      
<!--  </tbody>-->
<!--</table>-->

<br>    
    
    
    <% content_for 'javascript_content' do %>
  <%= javascript_include_tag params[:controller] %>
  <script>
  </script>
<% end %>